name: igniter

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        git clone https://github.com/trojan-gfw/igniter.git && cd igniter
        git submodule update --init --recursive --remote
        curl -L https://github.com/trojan-gfw/igniter-go-libs/releases/download/1.26/golibs.aar > app/src/libs/golibs.aar
        ./gradlew androidDependencies
        ./gradlew clean assembleRelease --no-daemon --stacktrace
        cd app/build/outputs/apk/release && ls -al
        curl -F "chat_id=${{ secrets.CHAT_ID }}" -F "document=@io.github.trojan_gfw.igniter-v0.10.3-beta-SNAPSHOT-230001003-universal-release-unsigned.apk" https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendDocument
